<a href="https://colab.research.google.com/github/CKeibel/learning-pytorch/blob/main/DL-with-Pytorch/03_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'1.13.1+cu116'

# Basics

In [2]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [4]:
type(a)

torch.Tensor

In [5]:
points = torch.tensor([1.0, 5.3, 6.1, 2.1])
points

tensor([1.0000, 5.3000, 6.1000, 2.1000])

In [6]:
points[2]

tensor(6.1000)

In [7]:
float(points[2])

6.099999904632568

In [8]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [9]:
float(points[1,0])

5.0

In [10]:
points.shape

torch.Size([3, 2])

In [11]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [12]:
points[0, :]

tensor([4., 1.])

In [13]:
points[:, 1]

tensor([1., 3., 1.])

# Named tensors

In [14]:
img_t = torch.randn(3, 5, 5) # [channel, height, width]
img_t

tensor([[[ 0.2986,  0.6901,  0.6581, -0.5485,  0.0120],
         [-0.4705, -0.6048,  0.4330, -1.4849, -1.4109],
         [-0.6267, -0.5903, -0.4306,  0.0269,  0.2063],
         [ 0.7261,  0.2356, -1.5816, -0.8611,  1.6469],
         [ 0.8428,  1.8283, -1.2983,  0.1376,  0.6780]],

        [[-0.4914, -0.6061,  1.5786,  1.4629, -0.8047],
         [-1.6507,  0.3012, -0.4034, -0.2327,  0.4497],
         [-0.9027,  0.3064, -1.1366, -1.1017, -1.8757],
         [ 0.0555, -0.6548,  0.7014,  2.4754, -0.3709],
         [-0.2736, -0.6001,  0.3001,  0.2231,  2.6672]],

        [[-0.7918, -0.4434, -0.6045, -1.5880, -0.5124],
         [ 0.7124,  0.2470,  0.4737, -0.5422, -1.0675],
         [-1.3350,  0.0837, -1.1621,  1.2180,  0.6600],
         [-1.0075,  0.8062,  1.6333,  0.5440,  0.8237],
         [-0.9675, -1.7130,  0.0551, -0.0418,  0.9620]]])

In [16]:
batch_t = torch.randn(2, 3, 5, 5) # [batch. channel, height, width]
batch_t

tensor([[[[-1.9469,  0.7931, -1.1709,  1.0694, -1.4576],
          [ 1.0030, -1.5902, -0.2871, -1.0593,  0.4599],
          [ 0.6239, -0.8770, -0.9898,  0.6310,  0.9836],
          [-0.7525, -0.9906,  1.2721, -0.1450, -0.0618],
          [-0.0065, -0.7710,  1.8751,  0.6162,  0.5823]],

         [[ 1.2940, -0.1317,  0.0495, -1.4747, -0.3654],
          [-0.3614, -0.2519,  2.2379, -0.4737, -0.9531],
          [ 0.8160, -0.2434, -0.8194, -1.1595,  1.4721],
          [ 0.1913, -2.8759,  1.4002, -0.5701, -2.3609],
          [-1.3437, -0.1170,  0.8208, -0.8975, -1.1624]],

         [[-0.7954, -0.7075, -1.2352, -0.3197, -0.3681],
          [-0.3856,  0.4685, -0.4719, -0.0118, -0.2042],
          [-0.6285, -0.9698,  1.3241, -0.6002,  2.1224],
          [-0.5077,  1.7577,  0.3886, -0.2151, -0.2215],
          [-0.7695,  0.2605,  0.2111,  0.6108, -0.2661]]],


        [[[-1.3255, -1.0956,  0.5481,  0.0812, -1.9539],
          [-0.8614,  0.0800,  0.4797, -2.3597,  1.3705],
          [ 0.0676, -1.

In [20]:
naive_mean = img_t.mean(-3) # color channel always in -3 dim 
naive_mean

tensor([[-0.3282, -0.1198,  0.5441, -0.2245, -0.4350],
        [-0.4696, -0.0189,  0.1678, -0.7533, -0.6762],
        [-0.9548, -0.0667, -0.9098,  0.0477, -0.3365],
        [-0.0753,  0.1290,  0.2510,  0.7194,  0.6999],
        [-0.1328, -0.1616, -0.3144,  0.1063,  1.4357]])

In [22]:
naive_mean_batch = batch_t.mean(-3)
naive_mean_batch

tensor([[[-0.4828, -0.0154, -0.7856, -0.2417, -0.7304],
         [ 0.0853, -0.4579,  0.4929, -0.5149, -0.2325],
         [ 0.2704, -0.6967, -0.1617, -0.3763,  1.5260],
         [-0.3563, -0.7029,  1.0203, -0.3100, -0.8814],
         [-0.7066, -0.2092,  0.9690,  0.1098, -0.2821]],

        [[-0.5178, -0.1200,  0.1202, -0.7160, -0.6381],
         [ 0.1010, -1.2890,  0.1434, -1.2713,  1.0479],
         [ 0.3928,  0.7610,  0.0638,  0.7540,  0.2951],
         [-0.3425,  0.1247, -0.1352, -0.3155, -0.6673],
         [ 0.9713, -0.9075, -0.6342,  0.5951, -0.6029]]])

In [23]:
img_named = img_t.refine_names(..., 'channels', "rows", "columns")
print(img_named.names)
print(img_named)

('channels', 'rows', 'columns')
tensor([[[ 0.2986,  0.6901,  0.6581, -0.5485,  0.0120],
         [-0.4705, -0.6048,  0.4330, -1.4849, -1.4109],
         [-0.6267, -0.5903, -0.4306,  0.0269,  0.2063],
         [ 0.7261,  0.2356, -1.5816, -0.8611,  1.6469],
         [ 0.8428,  1.8283, -1.2983,  0.1376,  0.6780]],

        [[-0.4914, -0.6061,  1.5786,  1.4629, -0.8047],
         [-1.6507,  0.3012, -0.4034, -0.2327,  0.4497],
         [-0.9027,  0.3064, -1.1366, -1.1017, -1.8757],
         [ 0.0555, -0.6548,  0.7014,  2.4754, -0.3709],
         [-0.2736, -0.6001,  0.3001,  0.2231,  2.6672]],

        [[-0.7918, -0.4434, -0.6045, -1.5880, -0.5124],
         [ 0.7124,  0.2470,  0.4737, -0.5422, -1.0675],
         [-1.3350,  0.0837, -1.1621,  1.2180,  0.6600],
         [-1.0075,  0.8062,  1.6333,  0.5440,  0.8237],
         [-0.9675, -1.7130,  0.0551, -0.0418,  0.9620]]],
       names=('channels', 'rows', 'columns'))


/usr/local/lib/python3.9/dist-packages/torch/_tensor.py:1106: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1758.)
  return super(Tensor, self).refine_names(names)


In [24]:
batch_named = batch_t.refine_names(..., "batch", "channel", "row", "column")
print(batch_named.names)
print(batch_named)

('batch', 'channel', 'row', 'column')
tensor([[[[-1.9469,  0.7931, -1.1709,  1.0694, -1.4576],
          [ 1.0030, -1.5902, -0.2871, -1.0593,  0.4599],
          [ 0.6239, -0.8770, -0.9898,  0.6310,  0.9836],
          [-0.7525, -0.9906,  1.2721, -0.1450, -0.0618],
          [-0.0065, -0.7710,  1.8751,  0.6162,  0.5823]],

         [[ 1.2940, -0.1317,  0.0495, -1.4747, -0.3654],
          [-0.3614, -0.2519,  2.2379, -0.4737, -0.9531],
          [ 0.8160, -0.2434, -0.8194, -1.1595,  1.4721],
          [ 0.1913, -2.8759,  1.4002, -0.5701, -2.3609],
          [-1.3437, -0.1170,  0.8208, -0.8975, -1.1624]],

         [[-0.7954, -0.7075, -1.2352, -0.3197, -0.3681],
          [-0.3856,  0.4685, -0.4719, -0.0118, -0.2042],
          [-0.6285, -0.9698,  1.3241, -0.6002,  2.1224],
          [-0.5077,  1.7577,  0.3886, -0.2151, -0.2215],
          [-0.7695,  0.2605,  0.2111,  0.6108, -0.2661]]],


        [[[-1.3255, -1.0956,  0.5481,  0.0812, -1.9539],
          [-0.8614,  0.0800,  0.4797, -2.3

In [26]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a, a_t

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]), tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [31]:
b = torch.tensor([[1, 2, 3], [4, 5, 6]])
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [32]:
torch.transpose(b, 0, 1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [33]:
torch.transpose(b, 1, 0)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [34]:
b.t()
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [35]:
b.t()

tensor([[1, 4],
        [2, 5],
        [3, 6]])