In [1]:
import torch
torch.__version__

'1.13.1+cu116'

# Basics

In [2]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [4]:
type(a)

torch.Tensor

In [5]:
points = torch.tensor([1.0, 5.3, 6.1, 2.1])
points

tensor([1.0000, 5.3000, 6.1000, 2.1000])

In [6]:
points[2]

tensor(6.1000)

In [7]:
float(points[2])

6.099999904632568

In [8]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [9]:
float(points[1,0])

5.0

In [10]:
points.shape

torch.Size([3, 2])

In [11]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [12]:
points[0, :]

tensor([4., 1.])

In [13]:
points[:, 1]

tensor([1., 3., 1.])

# Named tensors

In [14]:
img_t = torch.randn(3, 5, 5) # [channel, height, width]
img_t

tensor([[[-1.0714,  0.7227, -0.5737, -1.2088, -2.3827],
         [ 0.7370,  0.7265, -0.0058,  0.5456, -1.0798],
         [-0.9563,  0.4465, -0.4841, -1.4084,  1.2396],
         [ 0.1648,  0.7255, -1.0176, -0.3961,  1.2667],
         [-0.4282,  1.8189, -1.9494,  0.7315,  0.2276]],

        [[-1.4434,  2.0784,  0.2849, -0.4295,  0.3663],
         [ 0.1256, -0.3490,  0.2076,  0.1503, -1.2166],
         [-0.8474, -0.2729, -0.9191,  0.1632, -1.7498],
         [ 0.5047,  0.5355,  0.3769,  0.9339, -1.5844],
         [ 0.0509, -1.5843, -0.2231, -0.1557, -1.2971]],

        [[ 0.8181,  0.3747,  0.3752,  0.1938,  0.9288],
         [ 1.2059, -0.4715, -0.2159, -1.4894,  0.7375],
         [ 0.2599, -0.0332, -0.0941, -0.6221, -1.7500],
         [-0.7021, -1.5647, -0.3929,  1.0325,  0.2003],
         [ 0.1372, -0.7587,  1.2389, -0.3729, -0.6160]]])

In [15]:
batch_t = torch.randn(2, 3, 5, 5) # [batch. channel, height, width]
batch_t

tensor([[[[ 0.6844,  1.0396,  1.2126,  0.4277, -0.4749],
          [-1.0605, -0.2526, -0.2784,  1.6753, -1.7571],
          [-0.3885, -0.1276,  0.5997, -0.9648,  1.0531],
          [ 0.7124,  0.0458, -2.1058,  0.6450, -0.0145],
          [-1.7360,  1.5836, -0.0319, -2.2871,  0.7897]],

         [[ 1.8229, -0.1632, -0.5728,  0.5831,  1.3264],
          [-0.8084,  1.2089, -0.5431, -0.0116, -0.1253],
          [ 1.1339, -0.5829, -0.6747,  0.4423,  0.1714],
          [-1.2242,  1.2151,  0.9279,  2.2232,  1.0453],
          [ 0.7949,  0.3410,  0.1420, -1.4725, -1.3989]],

         [[-0.6060,  1.1249, -0.2220, -0.4567, -0.5230],
          [-0.7625,  0.5823,  1.3648,  0.2413,  0.3181],
          [-0.1713, -0.7775,  0.9715,  1.3315, -1.3996],
          [-1.7100, -0.5694,  0.8481, -1.0999,  0.3336],
          [-1.5439, -0.9536,  1.4069, -0.0737, -0.4823]]],


        [[[ 0.6860, -0.0272, -1.6665,  1.0137,  0.4084],
          [ 1.4944, -0.9612, -0.1143,  1.1143,  0.8748],
          [-0.6228, -0.

In [16]:
naive_mean = img_t.mean(-3) # color channel always in -3 dim 
naive_mean

tensor([[-0.5656,  1.0586,  0.0288, -0.4815, -0.3625],
        [ 0.6895, -0.0313, -0.0047, -0.2645, -0.5197],
        [-0.5146,  0.0468, -0.4991, -0.6224, -0.7534],
        [-0.0109, -0.1012, -0.3445,  0.5234, -0.0391],
        [-0.0800, -0.1747, -0.3112,  0.0676, -0.5619]])

In [17]:
naive_mean_batch = batch_t.mean(-3)
naive_mean_batch

tensor([[[ 0.6338,  0.6671,  0.1393,  0.1847,  0.1095],
         [-0.8772,  0.5128,  0.1811,  0.6350, -0.5214],
         [ 0.1913, -0.4960,  0.2988,  0.2697, -0.0584],
         [-0.7406,  0.2305, -0.1099,  0.5894,  0.4548],
         [-0.8283,  0.3236,  0.5057, -1.2778, -0.3638]],

        [[-0.3722, -0.0281, -0.5727,  0.1611, -0.3001],
         [ 0.3673, -0.6191,  0.1039,  0.4465,  0.7351],
         [-0.1148,  0.2787, -0.1559, -0.4758, -0.5261],
         [-0.5764, -0.0136, -0.6310,  0.8135,  0.3113],
         [ 0.0652,  0.2066, -0.1655,  0.8011,  0.4397]]])

In [18]:
img_named = img_t.refine_names(..., 'channels', "rows", "columns")
print(img_named.names)
print(img_named)

('channels', 'rows', 'columns')
tensor([[[-1.0714,  0.7227, -0.5737, -1.2088, -2.3827],
         [ 0.7370,  0.7265, -0.0058,  0.5456, -1.0798],
         [-0.9563,  0.4465, -0.4841, -1.4084,  1.2396],
         [ 0.1648,  0.7255, -1.0176, -0.3961,  1.2667],
         [-0.4282,  1.8189, -1.9494,  0.7315,  0.2276]],

        [[-1.4434,  2.0784,  0.2849, -0.4295,  0.3663],
         [ 0.1256, -0.3490,  0.2076,  0.1503, -1.2166],
         [-0.8474, -0.2729, -0.9191,  0.1632, -1.7498],
         [ 0.5047,  0.5355,  0.3769,  0.9339, -1.5844],
         [ 0.0509, -1.5843, -0.2231, -0.1557, -1.2971]],

        [[ 0.8181,  0.3747,  0.3752,  0.1938,  0.9288],
         [ 1.2059, -0.4715, -0.2159, -1.4894,  0.7375],
         [ 0.2599, -0.0332, -0.0941, -0.6221, -1.7500],
         [-0.7021, -1.5647, -0.3929,  1.0325,  0.2003],
         [ 0.1372, -0.7587,  1.2389, -0.3729, -0.6160]]],
       names=('channels', 'rows', 'columns'))


/usr/local/lib/python3.9/dist-packages/torch/_tensor.py:1106: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1758.)
  return super(Tensor, self).refine_names(names)


In [19]:
batch_named = batch_t.refine_names(..., "batch", "channel", "row", "column")
print(batch_named.names)
print(batch_named)

('batch', 'channel', 'row', 'column')
tensor([[[[ 0.6844,  1.0396,  1.2126,  0.4277, -0.4749],
          [-1.0605, -0.2526, -0.2784,  1.6753, -1.7571],
          [-0.3885, -0.1276,  0.5997, -0.9648,  1.0531],
          [ 0.7124,  0.0458, -2.1058,  0.6450, -0.0145],
          [-1.7360,  1.5836, -0.0319, -2.2871,  0.7897]],

         [[ 1.8229, -0.1632, -0.5728,  0.5831,  1.3264],
          [-0.8084,  1.2089, -0.5431, -0.0116, -0.1253],
          [ 1.1339, -0.5829, -0.6747,  0.4423,  0.1714],
          [-1.2242,  1.2151,  0.9279,  2.2232,  1.0453],
          [ 0.7949,  0.3410,  0.1420, -1.4725, -1.3989]],

         [[-0.6060,  1.1249, -0.2220, -0.4567, -0.5230],
          [-0.7625,  0.5823,  1.3648,  0.2413,  0.3181],
          [-0.1713, -0.7775,  0.9715,  1.3315, -1.3996],
          [-1.7100, -0.5694,  0.8481, -1.0999,  0.3336],
          [-1.5439, -0.9536,  1.4069, -0.0737, -0.4823]]],


        [[[ 0.6860, -0.0272, -1.6665,  1.0137,  0.4084],
          [ 1.4944, -0.9612, -0.1143,  1.1

In [20]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a, a_t

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]), tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [21]:
b = torch.tensor([[1, 2, 3], [4, 5, 6]])
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
torch.transpose(b, 0, 1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [23]:
torch.transpose(b, 1, 0)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [24]:
b.t()
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
b.t()

tensor([[1, 4],
        [2, 5],
        [3, 6]])

# Broadcasting

In [27]:
x = torch.ones(())
y = torch.ones(3,1)
z = torch.ones(1,3)
a = torch.ones(2, 1, 1)

In [31]:
y, y.shape

(tensor([[1.],
         [1.],
         [1.]]), torch.Size([3, 1]))

In [32]:
a, a.shape

(tensor([[[1.]],
 
         [[1.]]]), torch.Size([2, 1, 1]))

In [34]:
y*a, (y*a).shape

(tensor([[[1.],
          [1.],
          [1.]],
 
         [[1.],
          [1.],
          [1.]]]), torch.Size([2, 3, 1]))

In [36]:
c = torch.tensor([[1], [2], [3]])
c.shape

torch.Size([3, 1])

In [37]:
c*a, (c*a).shape

(tensor([[[1.],
          [2.],
          [3.]],
 
         [[1.],
          [2.],
          [3.]]]), torch.Size([2, 3, 1]))

In [38]:
y*z, (y*z).shape

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]), torch.Size([3, 3]))

In [39]:
c*z

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])